alter table TATOOSALON_PHOTO add constraint FK_TATOOSALON_PHOTO_ON_PORTFOLIO foreign key (PORTFOLIO_ID) references TATOOSALON_PORTFOLIO(ID);
create index IDX_TATOOSALON_PHOTO_ON_PORTFOLIO on TATOOSALON_PHOTO (PORTFOLIO_ID);
