alter table TATOOSALON_PORTFOLIO add constraint FK_TATOOSALON_PORTFOLIO_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references TATOOSALON_EMPLOYEE(ID);
create index IDX_TATOOSALON_PORTFOLIO_ON_EMPLOYEE on TATOOSALON_PORTFOLIO (EMPLOYEE_ID);
