alter table TATOOSALON_REGISTRATION add constraint FK_TATOOSALON_REGISTRATION_ON_CLIENT foreign key (CLIENT_ID) references TATOOSALON_CLIENT(ID);
create index IDX_TATOOSALON_REGISTRATION_ON_CLIENT on TATOOSALON_REGISTRATION (CLIENT_ID);
