-- begin TATOOSALON_REGISTRATION
alter table TATOOSALON_REGISTRATION add constraint FK_TATOOSALON_REGISTRATION_ON_CLIENT foreign key (CLIENT_ID) references TATOOSALON_CLIENT(ID)^
create index IDX_TATOOSALON_REGISTRATION_ON_CLIENT on TATOOSALON_REGISTRATION (CLIENT_ID)^
-- end TATOOSALON_REGISTRATION
-- begin TATOOSALON_PORTFOLIO
alter table TATOOSALON_PORTFOLIO add constraint FK_TATOOSALON_PORTFOLIO_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references TATOOSALON_EMPLOYEE(ID)^
create index IDX_TATOOSALON_PORTFOLIO_ON_EMPLOYEE on TATOOSALON_PORTFOLIO (EMPLOYEE_ID)^
-- end TATOOSALON_PORTFOLIO
-- begin TATOOSALON_SERVICE
alter table TATOOSALON_SERVICE add constraint FK_TATOOSALON_SERVICE_ON_SERVICE_CATEGORY foreign key (SERVICE_CATEGORY_ID) references TATOOSALON_SERVICE_CATEGORY(ID)^
alter table TATOOSALON_SERVICE add constraint FK_TATOOSALON_SERVICE_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references TATOOSALON_EMPLOYEE(ID)^
create index IDX_TATOOSALON_SERVICE_ON_SERVICE_CATEGORY on TATOOSALON_SERVICE (SERVICE_CATEGORY_ID)^
create index IDX_TATOOSALON_SERVICE_ON_EMPLOYEE on TATOOSALON_SERVICE (EMPLOYEE_ID)^
-- end TATOOSALON_SERVICE
-- begin TATOOSALON_PHOTO
alter table TATOOSALON_PHOTO add constraint FK_TATOOSALON_PHOTO_ON_NAME foreign key (NAME) references SYS_FILE(ID)^
alter table TATOOSALON_PHOTO add constraint FK_TATOOSALON_PHOTO_ON_PORTFOLIO foreign key (PORTFOLIO_ID) references TATOOSALON_PORTFOLIO(ID)^
create index IDX_TATOOSALON_PHOTO_ON_NAME on TATOOSALON_PHOTO (NAME)^
create index IDX_TATOOSALON_PHOTO_ON_PORTFOLIO on TATOOSALON_PHOTO (PORTFOLIO_ID)^
-- end TATOOSALON_PHOTO
-- begin TATOOSALON_FEEDBACK
alter table TATOOSALON_FEEDBACK add constraint FK_TATOOSALON_FEEDBACK_ON_REGISTRATION foreign key (REGISTRATION_ID) references TATOOSALON_REGISTRATION(ID)^
create index IDX_TATOOSALON_FEEDBACK_ON_REGISTRATION on TATOOSALON_FEEDBACK (REGISTRATION_ID)^
-- end TATOOSALON_FEEDBACK
-- begin TATOOSALON_REGISTRATION_SERVICE
alter table TATOOSALON_REGISTRATION_SERVICE add constraint FK_TATOOSALON_REGISTRATION_SERVICE_ON_REGISTRATION foreign key (REGISTRATION_ID) references TATOOSALON_REGISTRATION(ID)^
alter table TATOOSALON_REGISTRATION_SERVICE add constraint FK_TATOOSALON_REGISTRATION_SERVICE_ON_SERVICE foreign key (SERVICE_ID) references TATOOSALON_SERVICE(ID)^
create index IDX_TATOOSALON_REGISTRATION_SERVICE_ON_REGISTRATION on TATOOSALON_REGISTRATION_SERVICE (REGISTRATION_ID)^
create index IDX_TATOOSALON_REGISTRATION_SERVICE_ON_SERVICE on TATOOSALON_REGISTRATION_SERVICE (SERVICE_ID)^
-- end TATOOSALON_REGISTRATION_SERVICE
